version: "3.8"

services:
  app:
    build: .
    container_name: container-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    links:
      - db
    networks:
      - apphost
  db:
    image: mysql:5.7
    container_name: container-db
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE},
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3306:3306"
    networks:
      - apphost
networks:
  apphost:
    driver: bridge