version: "3.8"

services: 
  php:
    build: .
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./www:/var/www/html
    links: 
      - db
  db: 
    image: mysql:5.7
    volumes: 
      - /var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: containerdb
    ports: 
      - "3306:3306"
    